name: Project check

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Run checks
        run: |
          npm test